package:
  name: libradtran
  version: "2.0.3"

 
source:
  fn: libradtran-2.0.3.tar.gz
  md5: 8d2fd710eb0e1c35b716c976790c44a6
  url: http://www.libradtran.org/download/libradtran-2.0.3.tar.gz

requirements:
  build: 
    - python<3
    - gsl>=2.2.1
    - libopenblas
    - make 
    - {{ compiler('c') }}
    - {{ compiler('fortran') }} 
    - flex 
    - perl
    - libnetcdf
    - patchelf
    - netcdf-fortran
  run:
    - python>=3.8
    - gsl>=2.2.1
    - libopenblas
    - {{ compiler('c') }}
    - {{ compiler('fortran') }} 
    - make 
    - flex 
    - perl
    - libnetcdf
    - patchelf
    - netcdf-fortran
about:
  home: http://www.libradtran.org/
  license: GPL2
  summary: "libRadtran - library for radiative transfer - is a collection of C and Fortran functions and programs for calculation of solar and thermal radiation in the Earth's atmosphere. libRadtran is freely available under the GNU General Public License.

Authors: Bernhard Mayer, Claudia Emde, Josef Gasteiger, and Arve Kylling

Newest release: 2.0.2 from December 24, 2017.

Home page: http://www.libradtran.org"
