name: example-environment
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - python>=3.8
  - numpy
  - libradtran
  - rad_lib
  - pandas
  - matplotlib
  - scipy
# conda-lock -f environment.yml -p linux-64
  
